######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 19:59:30 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
LIBS += -lcv -lhighgui -lpthread

SOURCES += vision_ui.cpp QOpenCVWidget.cpp MyCameraWindow.cpp vision.c robot.c robot_main.c delay.c robot_threaded.c
HEADERS += QOpenCVWidget.cpp MyCameraWindow.h vision.h

