######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 8 19:59:30 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
LIBS += 

SOURCES += vision_test.cpp QOpenCVWidget.cpp MyCameraWindow.cpp
HEADERS += QOpenCVWidget.cpp MyCameraWindow.h
DEFINES += NO_VISION

